### PR TITLE
standardize indent

### PR DESCRIPTION
**Pull request by 7yl4r**
minor formatting fix.

### CODE REVIEW

**Comment by 7yl4r** [comment]
😞

**Comment by samapriya** [comment]
Hey @7yl4r 
Thanks for contributing I looked at your pull request after my commit so I am sorry to not integrate your change and by then the issue was fixed. I hope you are not disappointed I am sorry to close the request without a comment. Please feel free to make pull requests in the future if you see changes needed and I will definitely take a look before hand . Thank you

**Comment by 7yl4r** [comment]
I was just wondering what was up. I am glad to hear it got fixed. Next time I will aim higher with my PRs. 😄

**Comment by samapriya** [comment]
Any and all PRs are always welcome and I promise to look closely at my PRs before fixing things 😁

**Pull request closed without merging**
