### PR TITLE
Update rap.md

### PR DESCRIPTION
**Pull request by jornada-jw**

### CODE REVIEW

**Comment by samapriya** [comment]
Hi @jornada-jw 
Can you please comment on your relationship with the dataset? I usually ask the pull request come with specific comments like if you are a maintainer, owner, processor of current data and any additional information you could provide

**Comment by jornada-jw** [comment]
Hi Samapriya,

Thanks for reaching out. I am a Computational Biologist with the USDA Agricultural Research Service (ARS). The ARS is taking over stewardship of Rangeland Analysis Platform dataset from the University of Montana. Going forward, ARS will be the maintainer, owner, and processor of these data, which is why I requested an update to the information at awesome-gee-community-datasets. You can contact the previous maintainer, Brady Allred ***@***.***), for confirmation. I will be sure to provide the specified information with any future pull requests.

Thanks!


Jeb Williamson

USDA-ARS

Jornada Experimental Range

New Mexico State University

575-649-6234

***@***.******@***.***>

________________________________

**Comment by samapriya** [comment]
Thank you appreciat the input merging it now

**Comment by samapriya** [comment]
Hi @jornada-jw 
Wanted to thank you for your pull request and as a result of which you are included in the release 1.0.6 of the community catalog

```
Samapriya Roy, Valerie Pasquarella, Jeb Williamson, Erin Trochim, & Tyson Swetnam. (2023). samapriya/awesome-gee-
community-datasets: Community Catalog (1.0.6). Zenodo. https://doi.org/10.5281/zenodo.7817991
```

**Pull request merged**
